services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: churn_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  pgdata: